# Generated by Django 5.0.4 on 2024-05-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_alter_appointment_doctor_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='selected_time',
            field=models.TimeField(choices=[('07:00:00', 'Seven'), ('08:00:00', 'Eight'), ('09:00:00', 'Nine'), ('10:00:00', 'Ten'), ('11:00:00', 'Eleven'), ('13:00:00', 'Thirteen'), ('14:00:00', 'Fourteen'), ('15:00:00', 'Fifteen'), ('16:00:00', 'Sixteen'), ('17:00:00', 'Seventeen')], default='07:00:00'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='clinic_app.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='clinic_app.prescription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Patient', 'Patient'), ('Admin', 'Admin')], default='Patient', max_length=10),
        ),
    ]
