# Generated by Django 5.0.4 on 2024-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_service_prescription_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='service',
        ),
        migrations.AddField(
            model_name='prescription',
            name='services',
            field=models.ManyToManyField(to='clinic_app.service'),
        ),
    ]
