# Generated by Django 5.0.4 on 2024-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(blank=True, through='clinic_app.PrescriptionMedicine', to='clinic_app.medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='services',
            field=models.ManyToManyField(blank=True, to='clinic_app.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Patient', 'Patient')], default='Patient', max_length=10),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
