# Generated by Django 5.0.4 on 2024-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_bill_zalopay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='zalopay_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
