# Generated by Django 5.0.4 on 2024-05-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
