# Generated by Django 5.0.4 on 2024-05-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0011_appointment_notify'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionmedicine',
            unique_together={('medicine', 'prescription')},
        ),
    ]
